### ISSUE TITLE
error for No such file or directory

### ISSUE THREAD

**Issue by cuiyi129** [SimonRamstedt/ddpg#6]
Hi,

Im running the code as-is for the InvertedPendulum-v1 environment. The output log looks like:

I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "run.py", line 120, in <module>
    experiment.run(main)
  File "/home/cuiyi/ddpg/experiment.py", line 41, in run
    create(scriptdir, f, n)
  File "/home/cuiyi/ddpg/experiment.py", line 77, in create
    mkdir(path)
  File "/home/cuiyi/ddpg/experiment.py", line 255, in mkdir
    os.mkdir(path)
OSError: [Errno 2] No such file or directory: '../ddpg-results/experiment1'

what should I do to deal with the problem?

thanks.

**Comment by rmst** [comment]
That's a bug. I'll fix it in a sec. In the meantime you can create a folder called ddpg-results next to the ddpg folder to circumvent the problem.
Thanks for reporting!

**Comment by rmst** [comment]
Fixed it :)

**Comment by cuiyi129** [comment]
Thanks.That's bug has been solved.But the "simulation window" alway be gray or part of the screenshot.This is my computer's problem or the code's bug?
thanks.

**Comment by rmst** [comment]
Do you get the proper videos in ouput-folder/monitor? Have you tried with other non-mujoco envs?

**Comment by cuiyi129** [comment]
Hi! I don't get the proper videos in ouput-folder/monitor.The videos exist in the folder,but when I open it,it shows me error.And I tried with the basic cartpole env,the "simulation window" have no problem.

**Comment by rmst** [comment]
Hm, cartpole is not a continuous control environment so you should actually get an error. Have you tried Pendulum-v0 or MountainCarContinuous-v0? They are working for me. Maybe you could also try to reinstall gym and its dependencies. You can also run with `python ~/ddpg/run.py --outdir ~/ddpg-results/+  --fulltrace` to get longer error messages.

**Comment by cuiyi129** [comment]
oh,I'm sorry.I tried with the basic Pendulum-v0 (not cartpole),the "simulation window" have no problem.Thanks.Now,when I run the InvertedPendulum-v1 ,the "simulation window" alway be gray or part of the screenshot.And I don't get the proper videos in ouput-folder/monitor.So I think I should reinstall gym and its dependencies. Thanks.
